name: Node.js CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20, 21] #Node js versions

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies
      run: npm install

    - name: Run lint
      run: npm run lint # Adjust this if you have a different lint command

    - name: Run tests
      run: npm test

    - name: Run Prettier
      run: npm run prettier -- --check # Checks formatting without modifying files